node {

	stage ('Apply') {
		echo projectdir
		dir('/var/lib/jenkins/workspace/TerraformValidate/dc11-dot-khanh-networking') {
			sh 'terraform init'
			sh 'terraform apply -auto-approve'
		}		
	}

	stage ('Destroy') {
		dir('/var/lib/jenkins/workspace/TerraformValidate/dc11-dot-khanh-networking') {
			sh 'terraform destroy -auto-approve'
		}		
	}
}
